apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gitlab_project
  description: good sample hurray
  annotations:
    gitlab.com/project-id: '25929427'
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:guest
  lifecycle: production
