apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rellygood
  description: good sample hurray
  annotations:
    circleci.com/project-slug: 'github/wonjoyoo/nginx'
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:guest
  lifecycle: production
